### PR TITLE
Add csound-play-flags and csound-render-flags customizable variables

### PR DESCRIPTION
**Pull request by diegov**
I've added customizable variables to invoke csound with extra flags, like -+rtaudio=pulse when playing files, or -r.

### CODE REVIEW

**Comment by hlolli** [comment]
Awesome, I'll merge this later today, I'd love to see this added to the changelog. You're free to do it, I'll do it otherwise later today.

**Comment by diegov** [comment]
I'b be happy to, would this include a version bump? 0.2.2?

**Comment by hlolli** [comment]
nono, just write master in square brackets at the top.

**Comment by diegov** [comment]
Changelog updated, cheers.

**Comment by hlolli** [comment]
Thank YOU!

**Pull request merged**
