### PR TITLE
A few additions

### PR DESCRIPTION
**Pull request by rubenphilipp**
First of all, thanks a lot, Hlöðver, for this mesmerizing work! I am spreading the word of your project amongst my colleagues and receive -- from those within the Emacs universe, of course -- solely eulogistic feedback.

Anyway, I have written some extensions to your mode over the past months. The most important, for me, is the ability to **abort the compilation** of a Csound process with a simple key binding. This is done via the function `csound-abort-compilation` and the respective key-binding. I think this might be handy especially to those who are used to working with Csound-QT or similar environments. 
This leads me to the next, more broad, addition to your package. As it is sometimes useful **to lookup the definition**/reference or some opcode, I have added a module which resembles the SLIME lookup function which opens the documentation of a certain function(/method/macro etc.) from the context of a buffer via, in this case, `C-c C-d h`.

I hope, you will find these additions of some use and might incorporate them via the next commit.

Best regards
Ruben

### CODE REVIEW

**Comment by hlolli** [comment]
This looks fantastic, I will test your changes asap.

Looking trough the diffs, I notice some symptoms of your branch being based on older revision. I leave it as optional for you to look into, if you could run git rebase/git merge over the latest master branch. I can always pull and merge locally to test the changes as how it would look after your changes are merges, so it's not a big deal.

I'm always flattered to hear that people use this csound-mode emacs package. And nice to see some new features coming in, looking forward to review!

**Comment by rubenphilipp** [comment]
Thanks for your quick reply and warm words. I indeed worked on an older revision of your package. I will try to rebase my code to the current version, so that it is easier for you to merge the code into the master branch if desired. Anyway, you can of course -- as suggested -- test the additions manually.

Greetings
Ruben

**Comment by rubenphilipp** [comment]
Hey Hlöðver,

as you'll see, I've just managed to rebase my repository. 

Best
Ruben

**Comment by hlolli** [comment]
sincere apologies for the time this took, I tested it locally and there's no regression. I didn't know about

```elisp
(require 'browse-url)
(require 'thingatpt)
```

being built in libraries, very nice!

**Comment by rubenphilipp** [comment]
Hey Hlöðver,

no worries, we all have lots of things going on…
I'm delighted to see my additions being added to the csound-mode. Again, thanks a lot for your ongoing work. 
Both libraries are very handy and I'm glad, they are part of Emacs's core, as I am referring to them quite frequently.

Greetings from Essen
Ruben

**Comment by sohet** [comment]
Thank you Hlöðver for the quick fix, and thank you Ruben for the nice additions!

**Pull request merged**
